[package]
name = "csci5448_research_project_rust_code_examples"
version = "0.1.0"
edition = "2024"

[lib]
name = "csci5448_research_project_rust_code_examples"
path = "lib/rust/lib.rs"

[dependencies]
